// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzy1qWwN0Yp1a-YCZJ5VahRIqzVmEfwao',
    appId: '1:747172669614:web:ad07cd57fa1456402b253f',
    messagingSenderId: '747172669614',
    projectId: 'simple-chat-application-faca0',
    authDomain: 'simple-chat-application-faca0.firebaseapp.com',
    storageBucket: 'simple-chat-application-faca0.firebasestorage.app',
    measurementId: 'G-PJ8LX6NSM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj5bUbG4LVYUXdQi1bCDDb8EZL7V2pLRk',
    appId: '1:747172669614:android:f9930df0391519432b253f',
    messagingSenderId: '747172669614',
    projectId: 'simple-chat-application-faca0',
    storageBucket: 'simple-chat-application-faca0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs2kZpf2j3igCog_1nLhZqEKzACHYBrHA',
    appId: '1:747172669614:ios:d7a5af8c6bcf559e2b253f',
    messagingSenderId: '747172669614',
    projectId: 'simple-chat-application-faca0',
    storageBucket: 'simple-chat-application-faca0.firebasestorage.app',
    iosBundleId: 'com.example.simpleChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs2kZpf2j3igCog_1nLhZqEKzACHYBrHA',
    appId: '1:747172669614:ios:d7a5af8c6bcf559e2b253f',
    messagingSenderId: '747172669614',
    projectId: 'simple-chat-application-faca0',
    storageBucket: 'simple-chat-application-faca0.firebasestorage.app',
    iosBundleId: 'com.example.simpleChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzy1qWwN0Yp1a-YCZJ5VahRIqzVmEfwao',
    appId: '1:747172669614:web:d6fa936214a77d5f2b253f',
    messagingSenderId: '747172669614',
    projectId: 'simple-chat-application-faca0',
    authDomain: 'simple-chat-application-faca0.firebaseapp.com',
    storageBucket: 'simple-chat-application-faca0.firebasestorage.app',
    measurementId: 'G-K14GLTHZPL',
  );
}
